Fix the tox coverage target
This change prevents the following error:

$ tox -e coverage
...
coverage runtests: commands[1] | nosetests --with-coverage --cover-branches --cover-package honcho honcho/test/unit
...........................E......................
======================================================================
ERROR: Failure: ImportError (cannot import name 'coverage')
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
  File "/Users/marca/dev/git-repos/honcho/honcho/test/unit/test_manager.py", line 10, in <module>
    multiprocessing.Process = monkeypatch_process_for_coverage(multiprocessing.Process)
  File "/Users/marca/dev/git-repos/honcho/honcho/test/helpers.py", line 87, in monkeypatch_process_for_coverage
    from coverage.control import coverage
ImportError: cannot import name 'coverage'

It seems that in coverage==4.0a1 (which is somehow in our local devpi
server but not on PyPI now), "coverage" (lowercase 'c') changed to
"Coverage" (uppercase 'c'). So it seems wise to pin to coverage 3.x for
now.